apiVersion: batch/v1
kind: Job
metadata:
  name: dwd-hf-exporter
  labels:
    app: dwd-hf-exporter
spec:
  backoffLimit: 1 # retry only once on failure
  template:
    metadata:
      labels:
        app: dwd-hf-exporter
    spec:
      restartPolicy: Never # required for Jobs
      containers:
        - name: uv-python
          image: ghcr.io/astral-sh/uv:python3.12-bookworm
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command:
            - bash
            - -c
            - |
              set -ex

              apt update && apt install git nano -y

              git clone https://github.com/celine-eu/dwd-hf-exporter.git
              cd dwd-hf-exporter

              cp ../config.env .env

              uv sync

              echo "Deps installed. Starting exporter..."

              exec .venv/bin/python -u dwd_hf_exporter/main.py

          resources:
            requests:
              cpu: "1"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "16Gi"

          env:
            - name: PYTHONUNBUFFERED
              value: "1"

          volumeMounts:
            - name: dwd-hf-exporter-env
              mountPath: /app/config.env
              subPath: env

      volumes:
        - name: dwd-hf-exporter-env
          secret:
            secretName: dwd-hf-exporter-env
