version: "3"

tasks:
  apply:
    cmds:
      - kubectl delete secret dwd-hf-exporter-env || true
      - kubectl create secret generic dwd-hf-exporter-env --from-file=env=.env
      - kubectl apply -f deployment.yaml
      - sleep 2
      - kubectl logs deployment/dwd-hf-exporter -f

  delete:
    cmds:
      - kubectl delete secret dwd-hf-exporter || true
      - kubectl delete -f deployment.yaml || true

  bash:
    cmds:
      - kubectl exec -it dwd-hf-exporter -- bash

  logs:
    cmds:
      - kubectl logs dwd-hf-exporter -f
